name: Update Stats
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update STATS.md
        run: |
          gh api repos/${{ github.repository }} --jq '{stars:.stargazers_count,forks:.forks_count,issues:.open_issues_count}' > stats.json
          echo "# Stats" > STATS.md
          cat stats.json >> STATS.md
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add STATS.md || true
          git commit -m "ci: update STATS.md [skip ci]" || true
          git push || true
